#!/bin/bash
# Pasos para actualizar el repositorio después de agregar .gitignore

echo "📦 PASO 1: Hacer commit de los cambios actuales"
echo "================================================"
echo ""
echo "Ejecutar:"
echo "  git commit -m 'chore: add .gitignore and remove tracked DB/cache files'"
echo ""
read -p "Presiona ENTER después de hacer el commit..."

echo ""
echo "🔍 PASO 2: Verificar el estado"
echo "================================================"
git status
echo ""
read -p "Presiona ENTER para continuar..."

echo ""
echo "⬆️  PASO 3: Push al repositorio remoto"
echo "================================================"
echo ""
echo "Ejecutar:"
echo "  git push origin main"
echo ""
echo "⚠️  NOTA: Si ya subiste archivos grandes anteriormente,"
echo "   es posible que el push falle por tamaño de archivos."
echo ""
read -p "Presiona ENTER después de intentar el push..."

echo ""
echo "🧹 PASO 4 (OPCIONAL): Limpiar historial de archivos grandes"
echo "=============================================================="
echo ""
echo "Si el push falla por archivos grandes en el historial:"
echo ""
echo "Opción A - BFG Repo-Cleaner (recomendado):"
echo "  1. Instalar: brew install bfg"
echo "  2. Ejecutar: bfg --strip-blobs-bigger-than 50M"
echo "  3. Limpiar: git reflog expire --expire=now --all && git gc --prune=now --aggressive"
echo "  4. Push forzado: git push --force"
echo ""
echo "Opción B - git filter-repo:"
echo "  1. Instalar: brew install git-filter-repo"
echo "  2. Ejecutar: git filter-repo --strip-blobs-bigger-than 50M"
echo "  3. Push forzado: git push --force"
echo ""
echo "⚠️  ADVERTENCIA: Estas operaciones reescriben el historial de Git."
echo "   Solo úsalas si estás seguro y has notificado al equipo."
echo ""
echo "✅ Script completado!"
